export const recipeData = [
  {
    id: "1",
    title: "chilli",
    image:
      "https://144f2a3a2f948f23fc61-ca525f0a2beaec3e91ca498facd51f15.ssl.cf3.rackcdn.com/uploads/food_portal_data/recipes/recipe/hero_article_image/2817/letterbox_Veggie-chilli593_copy.jpg",
    catagory: "main",
    cuisine: "mexican",
    servings: 4,
    calories: 353,
    ingredients: [
      "500g turkey mince",
      "1 red onion",
      "1 red onion",
      "1 carrot",
      "1 cup mushrooms",
      "some tomatoe sauce",
      "400g kidney beans",
      "150g sweetcorn",
      "3 crushed garlic cloves",
      "1 tsp ground cumin",
      "1 tsp dried oregano",
      "1 tbsp smoked paprika",
      "1 tbsp cajan spice",
      "1 tbsp chilli powder",
      "4 tbsp light soy sauce",
      "2 tbsp lea and perrins",
      "4 tbsp maple syrup",
      "2 tsp chipotle",
    ],
    instructions: [
      "finley chop red onion, mushrooms, pepper and carrot",
      " add tomato sauce, kedney beans, sweetcorn, spices, soy sauce, lean & perrins and maple syrup into a saucpan",
      "heat the sauce on the hob",
      "while the sauce is heating, brown the turkey mince in a large wok, add in red onion and pepper, add in mushrooms and carrot",
      "once cooked pour the sauce from the pan into the wok and simmer for 5 minutes",
    ],
  },
  {
    id: "2",
    title: "banomellets",
    image:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/190403-pancakes-066-copy-1554497284.jpeg?crop=0.777xw:0.584xh;0.115xw,0.315xh&resize=1200:*",
    catagory: "dessert",
    cuisine: "unlisted",
    servings: 1,
    calories: 170,
    ingredients: ["1 egg", "1 banana"],
    instructions: [
      "beat egg in a jug",
      "mash banana",
      "mix mashed banana and egg together",
      "pour mix into frying pan and cook on low-medium heat until light brown then flip and repeat",
    ],
  },
  {
    id: "3",
    title: "Chicken Fajitas",
    image:
      "https://www.santamariaworld.com/optimized/recipe-large/globalassets/uk/general/fajitas-1_lowjpg.jpg",
    catagory: "main",
    cuisine: "mexican",
    servings: 2,
    calories: 407,
    ingredients: [
      "2 chicken breasts",
      "1 red onion",
      "1 cup mushrooms",
      "1 red pepper",
      "some tomatoe sauce",
      "1 crushed garlic cloves",
      "2 tsp smoked paprika",
      "1 tbsp cajan spice",
      "2 tsp chilli powder",
      "2 tbsp light soy sauce",
      "1 tbsp lea and perrins",
      "2 tbsp maple syrup",
      "2 large tortillas",
    ],
    instructions: [
      "finley chop red onion, mushrooms, and pepper",
      " add tomato sauce, spices, soy sauce, lean & perrins and maple syrup into a saucpan",
      "heat the sauce on the hob",
      "while the sauce is heating, brown the chicken in a large wok, add in red onion and pepper, add in mushrooms",
      "once cooked pour the sauce from the pan into the wok and simmer for 5 minutes",
      "add contents of the wok to tortilas and serve",
    ],
  },
  {
    id: "4",
    title: "almond butter fudge",
    image:
      "https://ketogenic.com/wp-content/uploads/2020/02/Salted-Butter-Fudge.jpg",
    catagory: "snack",
    cuisine: "british",
    servings: 12,
    calories: 100,
    ingredients: [
      "1/2 cup of almond butter",
      "2.5 tbsp coconut oil",
      "2.5 tbsp maple syrup",
    ],
    instructions: [
      "Combine all of the ingredients in a saucepan over a low heat until melted",
      "Transfer into silicone molds",
      "Put in the freezer for a few hours until set",
      "You can have them as they are or before you put them into the freezer you can top them with things like chia seeds, cacao nibs, other seeds, dried berries etc",
      "Keep in the fridge/freezer until ready to eat",
    ],
  },
  {
    id: "5",
    title: "pear custard pie",
    image:
      "https://www.dinneratthezoo.com/wp-content/uploads/2015/04/pear-custard-pie-new.jpg",
    catagory: "dessert",
    cuisine: "british",
    servings: 6,
    calories: 227,
    ingredients: [
      "4 pears",
      "1/4 cup of unsalted butter",
      "3 eggs",
      "3/4 cup of skimmed milk",
      "1/4 tsp salt",
      "1/3 cup of coconut sugar",
      "1/3 cup of all purpose flour",
      "2 tsp vanilla extract",
    ],
    instructions: [
      "preheat the oven to 180 degrees C and coat baking tin with coconut oil",
      "cover ther bottom of the pan with pear slices",
      "blend together butter, eggs, milk, salt, sugar, flour and vanilla extract until smooth",
      "pour the batter over the pears and bake for 40-45 minutes until custard is golden brown",
    ],
  },
  {
    id: "6",
    title: "Chicken enchiladas",
    image:
      "https://www.inspiredtaste.net/wp-content/uploads/2020/03/Easy-Chicken-Enchilada-Recipe-1-1200-1200x800.jpg",
    catagory: "main",
    cuisine: "mexican",
    servings: 4,
    calories: 471,
    ingredients: [
      "4 chicken breasts",
      "1 red onion",
      "1 cup mushrooms",
      "1 red pepper",
      "some tomatoe sauce",
      "3 crushed garlic cloves",
      "1 tbsp smoked paprika",
      "2 tbsp cajan spice",
      "1 tbsp chilli powder",
      "4 tbsp light soy sauce",
      "2 tbsp lea and perrins",
      "4 tbsp maple syrup",
      "4 large tortillas",
    ],
    instructions: [
      "finley chop red onion, mushrooms, and pepper",
      " add tomato sauce, spices, soy sauce, lean & perrins and maple syrup into a saucpan",
      "heat the sauce on the hob",
      "while the sauce is heating, brown the chicken in a large wok, add in red onion and pepper, add in mushrooms",
      "set aside a ladle of sauce to coat the enchiladas",
      "once cooked pour the sauce from the pan into the wok and simmer for 5 minutes",
      "add contents of the wok to tortilas and and place in a baking dish",
      "coat the tortillas with the remaining sauce, sprinkle with grated cheese, chives and lea and perrins",
      "bake in the oven for 25 minutes at 180 degrees C",
    ],
  },
];
